version: '3.8'

services:
  db:
    build:
      context: ./pgvector-db
      args:
        - PG_MAJOR=16
        - PGVECTOR_VERSION=v0.6.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    user: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h localhost -p 5432"]
      interval: 1s
      timeout: 10s
      retries: 5

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  web:
    build: ./garden_django
    command: >
      sh -c "until pg_isready -h db -p 5432 -U garden_db; do sleep 1; done &&
            python manage.py migrate &&
            python create_superuser.py &&
            python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./garden_django:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  qcluster:
    build: ./garden_django
    command: sh -c "until pg_isready -h db -p 5432 -U garden_db; do sleep 1; done && python manage.py qcluster"
    volumes:
      - ./garden_django:/code
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
