# Generated by Django 4.2.11 on 2024-04-20 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='telegram_id',
        ),
    ]
