# Generated by Django 4.2.11 on 2024-04-21 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_use_api_key_customuser_use_sytsem_api_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='use_sytsem_api_key',
            new_name='use_system_api_key',
        ),
    ]
