# Generated by Django 4.2.11 on 2024-04-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_use_sytsem_api_key_customuser_use_system_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='max_chunk_size_setting',
            field=models.IntegerField(default=600),
        ),
    ]
