# Generated by Django 3.2.25 on 2024-04-01 20:27

from django.contrib.postgres.fields import ArrayField
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0002_enable_vector_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideapart',
            name='embedding_new',
            field=ArrayField(base_field=models.FloatField(), size=None, null=True, blank=True),
        ),
        migrations.RemoveField(
            model_name='ideapart',
            name='embedding',
        ),
        migrations.RenameField(
            model_name='ideapart',
            old_name='embedding_new',
            new_name='embedding',
        ),
    ]