# Generated by Django 3.2.25 on 2024-04-01 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0004_auto_20240401_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='new_embedding',
            new_name='embedding',
        ),
        migrations.RenameField(
            model_name='ideapart',
            old_name='new_embedding',
            new_name='embedding',
        ),
    ]
