# Generated by Django 4.2.11 on 2024-04-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0005_auto_20240401_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='reserve_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
