# Generated by Django 4.2.11 on 2024-04-13 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0006_idea_reserve_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Idea',
            new_name='Seed',
        ),
        migrations.RenameModel(
            old_name='IdeaPart',
            new_name='Snippet',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='idea',
            new_name='seed',
        ),
    ]
