# Generated by Django 4.2.11 on 2024-04-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0007_rename_idea_seed_rename_ideapart_snippet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seed',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seed',
            name='topics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
