# Generated by Django 4.2.11 on 2024-04-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0008_alter_seed_tags_alter_seed_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seed',
            name='reserve_url',
        ),
        migrations.AddField(
            model_name='seed',
            name='reserve_file',
            field=models.FileField(blank=True, null=True, upload_to='reserves/'),
        ),
    ]
