# Generated by Django 4.2.11 on 2024-05-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0010_garden_gardenmembership_garden_visitors_seed_garden'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='start_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
